services:
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
  mongodb: # Does it need to have specific name like mongo or can it be anything? Why does it need so much config in comparison to redis?
    image: 'mongo:latest'
    ports: 
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped
volumes:
  mongodb_data:
    driver: local
