spring:
  application:
    name: rate-limiter
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis

server:
  address: 0.0.0.0
  port: 8080

rate-limit:
  fallback:
    algorithm: TOKEN_BUCKET
    parameters:
      capacity: 3
      refillRate: 1
  endpoints:
    - path: /api/test
      user-tiers:
        free:
          algorithm: TOKEN_BUCKET
          parameters:
            capacity: 5
            refillRate: 0
        premium:
          algorithm: LEAKY_BUCKET
          parameters:
            capacity: 5
            leakRate: 1
    - path: /api/test/v2
      user-tiers:
        free:
          algorithm: LEAKY_BUCKET
          parameters:
            capacity: 10
            flowRate: 1
    - path: /api/config
      algorithm: TOKEN_BUCKET
      parameters:
        capacity: 20
        refillRate: 2
  redis:
    ttl: 600000
  security:
    enabled: true
    trusted-proxies:
      - 127.0.0.1
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
    log-suspicious: true

# Tell Micrometer to add this name as a tag to every single metric
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

      # ASK: What should be used if req to a particular endpoint is sent, where user doesn't have config for that endpoint. It should be default fallback algorithm or the algorithm for that particular endpoint. This is used to determine the algorithm to use if no specific configuration is found for the endpoint.
