spring:
  application:
    name: rate-limiter
  redis:
    host: redis
    port: 6379
  cache:
    type: redis

server:
  address: 0.0.0.0
  port: 8080

rate-limiter:
  properties:
    fallback:
      algorithm: TOKEN_BUCKET
    redis:
      ttl: 600000
